-- Roles + auditoría + solicitudes
-- Ejecuta en Supabase → SQL Editor.
--
-- Requisitos:
-- - Auth habilitado en tu proyecto (Supabase Auth).
-- - Extensión pgcrypto (para gen_random_uuid) normalmente ya está.

-- 1) Perfiles / roles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  username text,
  role text not null default 'user' check (role in ('admin', 'user')),
  created_at timestamptz not null default now()
);

comment on table public.profiles is 'Perfil por usuario (Auth). role=admin|user.';

-- Si `profiles` ya existía de antes, asegura que `username` exista.
alter table public.profiles
  add column if not exists username text;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, username, role)
  values (new.id, new.email, split_part(coalesce(new.email, ''), '@', 1), 'user')
  on conflict (id) do update
    set email = excluded.email,
        username = excluded.username;
  return new;
end;
$$;

-- Backfill username para perfiles existentes (si aplica)
update public.profiles
set username = split_part(coalesce(email, ''), '@', 1)
where (username is null or btrim(username) = '') and email is not null;

-- Username único (opcional, recomendado)
create unique index if not exists profiles_username_uidx on public.profiles (username);

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();

-- Helper para políticas
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- Backfill perfiles faltantes (evita 406 al leer profiles con .single()).
insert into public.profiles (id, email, username, role)
select u.id, u.email, split_part(coalesce(u.email, ''), '@', 1), 'user'
from auth.users u
left join public.profiles p on p.id = u.id
where p.id is null;

-- 2) Auditoría (historial)
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_id uuid references auth.users(id),
  actor_email text,
  action text not null,
  table_name text,
  record_id uuid,
  metadata jsonb
);

comment on table public.audit_log is 'Bitácora de acciones (solo admin puede leer).';

-- Inserta auditoría sin depender de permisos del usuario (trigger-safe)
create or replace function public.audit_write(
  p_action text,
  p_table_name text,
  p_record_id uuid,
  p_metadata jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text;
begin
  select p.email into v_email
  from public.profiles p
  where p.id = auth.uid();

  insert into public.audit_log (actor_id, actor_email, action, table_name, record_id, metadata)
  values (auth.uid(), v_email, p_action, p_table_name, p_record_id, p_metadata);
end;
$$;

-- Permite que el frontend (authenticated) ejecute audit_write vía RPC.
grant execute on function public.audit_write(text, text, uuid, jsonb) to authenticated;

-- 3) Solicitudes de producto (usuario solicita; admin gestiona)
create table if not exists public.solicitudes (
  id uuid primary key default gen_random_uuid(),
  producto_id uuid not null references public.productos(id) on delete restrict,
  cantidad numeric not null check (cantidad > 0),
  nota text,
  status text not null default 'pendiente' check (status in ('pendiente', 'aprobada', 'rechazada', 'entregada')),
  requested_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.solicitudes is 'Solicitudes de producto. Usuarios crean; admin ve todo y cambia status.';

create or replace function public.solicitudes_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists solicitudes_set_updated_at on public.solicitudes;
create trigger solicitudes_set_updated_at
  before update on public.solicitudes
  for each row
  execute function public.solicitudes_touch_updated_at();

-- 4) Triggers de auditoría (productos + solicitudes)
create or replace function public.audit_productos_trg()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (tg_op = 'INSERT') then
    perform public.audit_write('producto_creado', 'productos', new.id, jsonb_build_object('codigo', new.codigo, 'nombre', new.nombre));
    return new;
  elsif (tg_op = 'UPDATE') then
    perform public.audit_write(
      'producto_actualizado',
      'productos',
      new.id,
      jsonb_build_object(
        'codigo', new.codigo,
        'nombre', new.nombre,
        'stock_anterior', old.stock_actual,
        'stock_nuevo', new.stock_actual
      )
    );
    return new;
  elsif (tg_op = 'DELETE') then
    perform public.audit_write('producto_eliminado', 'productos', old.id, jsonb_build_object('codigo', old.codigo, 'nombre', old.nombre));
    return old;
  end if;
  return null;
end;
$$;

drop trigger if exists productos_audit_trg on public.productos;
create trigger productos_audit_trg
  after insert or update or delete on public.productos
  for each row
  execute function public.audit_productos_trg();

create or replace function public.audit_solicitudes_trg()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (tg_op = 'INSERT') then
    perform public.audit_write(
      'solicitud_creada',
      'solicitudes',
      new.id,
      jsonb_build_object('producto_id', new.producto_id, 'cantidad', new.cantidad, 'status', new.status)
    );
    return new;
  elsif (tg_op = 'UPDATE') then
    perform public.audit_write(
      'solicitud_actualizada',
      'solicitudes',
      new.id,
      jsonb_build_object('status_anterior', old.status, 'status_nuevo', new.status)
    );
    return new;
  end if;
  return null;
end;
$$;

drop trigger if exists solicitudes_audit_trg on public.solicitudes;
create trigger solicitudes_audit_trg
  after insert or update on public.solicitudes
  for each row
  execute function public.audit_solicitudes_trg();

