import type { InventoryItem } from '../../types/inventory'

export const seedItems: InventoryItem[] = [
  {
    id: 'item_cmp_001',
    codigo: 'CMP-001',
    nombre: 'Resistencia 10kΩ',
    descripcion: '1/4W, 1%, axial',
    categoriaId: 'cat_componentes',
    stockActual: 500,
    stockMinimo: 100,
    unidad: 'piezas',
    ubicacion: { area: 'Almacén principal', ubicacion: 'Estante A1' },
    costoUnitario: 0.5,
    proveedorId: 'prov_digikey',
    partNumber: 'RES-10K-1%',
    fabricante: 'Yageo',
    estado: 'Disponible',
    ultimaEntradaISO: '2026-04-20T14:30:00.000Z',
  },
  {
    id: 'item_her_002',
    codigo: 'HER-002',
    nombre: 'Cautín 60W',
    descripcion: 'Para producción',
    categoriaId: 'cat_herramientas',
    stockActual: 10,
    stockMinimo: 2,
    unidad: 'piezas',
    ubicacion: { area: 'Área de producción', ubicacion: 'Mesa 2' },
    costoUnitario: 250,
    proveedorId: 'prov_steren',
    estado: 'En uso',
  },
  {
    id: 'item_mat_003',
    codigo: 'MAT-003',
    nombre: 'Estaño 0.8mm',
    descripcion: 'Rollo 100g',
    categoriaId: 'cat_materiales',
    stockActual: 0,
    stockMinimo: 5,
    unidad: 'piezas',
    ubicacion: { area: 'Almacén principal', ubicacion: 'Caja M3' },
    costoUnitario: 120,
    proveedorId: 'prov_local',
    estado: 'Disponible',
  },
]

